# Change these first
owner: brose-ebike # GitHub organization
repo: cloud-status # The name of this repository

sites:
  - name: Brose E-Bike App
    url: $STATUS_URL_APP
    maxResponseTime: 5000
  - name: Brose E-Bike SDK
    url: $STATUS_URL_SDK
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.brose.bike
  name: Brose E-Bike Cloud
  introTitle: ""
  introMessage: ""
  favicon: https://static.brose.bike/images/generic/brose-favicon.ico
  logoUrl: https://static.brose.bike/images/generic/brose-logo.png
  themeUrl: https://min.gitcdn.link/cdn/brose-ebike/cloud-status/master/assets/brose-theme.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.brose-ebike.com

