# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Brose E-Bike App
    url: $STATUS_URL_APP
    maxResponseTime: 5000
  - name: Brose E-Bike SDK
    url: $STATUS_URL_SDK
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: brose-ebike.github.io
  baseUrl: /cloud-status
  logoUrl: https://static.brose.bike/images/generic/brose-logo.png
  name: Brose E-Bike Cloud
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

