# Change these first
owner: brose-ebike # GitHub organization
repo: cloud-status # The name of this repository
skipDeleteIssues: true

sites:
  - name: Brose E-Bike App
    url: $STATUS_URL_APP
    maxResponseTime: 5000
    icon: https://static.brose.bike/images/generic/brose-logo-rect.png
  - name: Brose E-Bike SDK
    url: $STATUS_URL_SDK
    maxResponseTime: 5000
    icon: https://static.brose.bike/images/generic/brose-logo-rect.png
  - name: Brose Rider UI
    url: https://rider.brose.bike
    maxResponseTime: 5000
    icon: https://static.brose.bike/images/generic/brose-logo-rect.png
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.brose.bike
  name: Brose E-Bike Cloud
  introTitle: ""
  introMessage: ""
  favicon: https://static.brose.bike/images/generic/brose-favicon.ico
  logoUrl: https://static.brose.bike/images/generic/brose-logo.png
  themeUrl: https://min.gitcdn.link/cdn/brose-ebike/cloud-status/ae1d5779fab5fd5e58161c85ffd2922629fdd447/assets/brose-theme.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://rider.brose.bike
    - title: Imprint
      href: https://app.prod.brose.bike/api/v1/legal/imprint/en/latest/redirect
i18n:
  footer: Brose Antriebstechnik GmbH und Co. Kommanditgesellschaft, Berlin, Powered by [Upptime](https://upptime.js.org/).
  liveStatus: System Status
