# Change these first
owner: brose-ebike # GitHub organization
repo: cloud-status # The name of this repository

sites:
  - name: Brose E-Bike App
    url: $STATUS_URL_APP
    maxResponseTime: 5000
  - name: Brose E-Bike SDK
    url: $STATUS_URL_SDK
    maxResponseTime: 5000
  - name: Komoot
    url: "https://auth-api.main.komoot.net/"
    maxResponseTime: 5000
    icon: "https://www.komoot.de/icons/favicon.11dce39abcb07b8a81b4c3be7218631f.png"
  - name: Strava
    url: "https://www.strava.com/"
    maxResponseTime: 5000
    icon: "https://d3nn82uaxijpm6.cloudfront.net/apple-touch-icon-180x180.png"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.brose.bike
  name: Brose E-Bike Cloud
  introTitle: ""
  introMessage: ""
  favicon: https://static.brose.bike/images/generic/brose-favicon.ico
  logoUrl: https://static.brose.bike/images/generic/brose-logo.png
  themeUrl: https://min.gitcdn.link/cdn/brose-ebike/cloud-status/c5ce1384c861ed5eb86469f393c1acb631465c40/assets/brose-theme.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.brose-ebike.com
    - title: Imprint
      href: https://www.brose-ebike.com/de-de/impressum.html
i18n:
  footer: Brose Antriebstechnik GmbH und Co. Kommanditgesellschaft, Berlin, Powered by [Upptime](https://upptime.js.org/).
  liveStatus: System Status
